export const LOGIN_BY_CUSTOMER = 'LOGIN_BY_CUSTOMER'
export const SIGNUP = 'SIGNUP'

export const GET_CUSTOMERS = 'GET_CUSTOMERS'
export const GET_CUSTOMER_BY_ID = 'GET_CUSTOMER_BY_ID'
export const ADD_CUSTOMER = 'ADD_CUSTOMER'

export const GET_WAREHOUSES = 'GET_WAREHOUSES'
export const GET_WAREHOUSE_BY_ID = 'GET_GET_WAREHOUSE_BY_ID'
export const ADD_WAREHOUSE = 'ADD_WAREHOUSE'
export const ACCESS_WAREHOUSE = 'ACCESS_WAREHOUSE'
export const GET_WAREHOUSES_BY_CUSTOMER_ID = 'GET_WAREHOUSES_BY_CUSTOMER_ID'